OMPSS_HOME=$(HOME)/scratch-local/ompss/16-dev
MCXX_HOME=$(OMPSS_HOME)/mcxx-2.1-acc
NANOS_HOME=$(OMPSS_HOME)/nanox-0.13a-acc

PGI_HOME=/usr/local/pgi/linux86-64/16.10

CC=gcc
MCC=$(MCXX_HOME)/bin/mcc
PGCC=$(PGI_HOME)/bin/pgcc

CFLAGS=-Wall -g
MCCFLAGS=--ompss -g -O3
PGCFLAGS=-g -O3 -acc -ta=tesla:cuda8.0,cc50,cc60 -Minline -Minfo=accel
